name: Data Science - Analyses Statistiques - Data Visualisation
description: Pour révéler la valeur de vos données
repo: https://github.com/dominiqueemmanuel/dominiqueemmanuel.github.io

url: https://dominiqueemmanuel.github.io/
permalink: "articles/:title"

exclude:
  - 404.html

highlighter: rouge

markdown: kramdown

comments: true

gems:
- jekyll-redirect-from